In [19]:
from PIL import Image
import numpy as np

imgPath="../assest/lean.jpg"

def test():
 matrix=np.zeros((3,3),dtype=np.uint8) #numpy.ndarray
 for i in range(0,3):
  matrix[:,2]=3
  matrix[i,i]=1
 print(matrix)

 #print(matrix)
def shift():
 matrix=np.zeros((512,512),dtype=np.uint8) #numpy.ndarray
 for i in range(0,512):
  matrix[:,511]=10
  matrix[i,i]=1
 src_img=np.array(Image.open(imgPath).convert('L')) #numpy.ndarry

 dst_img=np.matmul(matrix,src_img)
 result=Image.fromarray(dst_img.astype('uint8'))
 result.save("result.jpeg")


 pass
def rotate():
 pass
def mirror():
 pass
test()

[[1 0 3]
 [0 1 3]
 [0 0 1]]
